### ISSUE TITLE
Proposal for name spacing pull request - rename BreezeComponent to Component

### ISSUE THREAD

**Issue by eugenevdm** [faisalfjri/breeze-vue-api#2]
I was wondering if this pull request that I wanted to do would be useful. It's modelled after Laravel Breeze pull request #179, [Remove "Breeze" component prefix](https://github.com/laravel/breeze/pull/179)

The idea would be to limit the scope to just the Breeze component renames. If you are happy with the changes, then I could possibly attempt more of the renaming that happened in that pull request. But for now, just those renames.

The reason for doing this would be to align this repository  with the official Laravel Breeze repository as much as possible and then hopefully keep it future. I found this repository very useful because I'm developing an offline PWA so I can't use Inertia and server side routing.

@faisalfjri  what do you think?

**Comment by faisalfjri** [comment]
@eugenevdm I think it's a good idea

**Comment by eugenevdm** [comment]
Cool thanks @faisalfjri here is my attempt: https://github.com/faisalfjri/breeze-vue-api/pull/3
