### ISSUE TITLE
Change Welcome.vue so it is more different form Laravels default installation page

### ISSUE THREAD

**Issue by andersbc** [faisalfjri/breeze-vue-api#4]
Not really a technical issue, but a suggestion: 
I spent an hour trying to figure out why my Nginx setup served me the default Laravel welcome *backend* page, or redirected to it, when hitting my new vue *frontend*, made with this project. 
I finally realized that in fact I was getting the frontend. The projects' welcome page looks almost identical to Laravels default installation page. except for dim login links, etc. Consider changing it to make it more obvious that the installation is fine. 

+ thanks for the project :-)

**Comment by faisalfjri** [comment]
@andersbc if you run the command

`php artisan breeze:install api`

then the welcome page in backend laravel will not appear anymore and will change to laravel:version.

like this 
`{
  "Laravel": "9.45.0"
}`

**Comment by andersbc** [comment]
@faisalfjri  I know :-) but I was confused by this projects' welcome page looking almost exactly like Laravels' default welcome page. I thought I was somehow hitting the old laravel backend instead of getting my new vuejs frontend .. so I spent time debugging my Nginx/Docker setup, thinking something was wrong  Maybe make it more obvious in the welcome.vue page that this is, in fact, the vuejs frontend. Thank you for your reply :-)
