### ISSUE TITLE
useStorage for userLogin form values not long work correctly

### ISSUE THREAD

**Issue by alvarofvr** [faisalfjri/breeze-vue-api#5]
Hi, there is a problem with usage of localStorage for store the userLogin form values (email and password) in the Login.vue (https://github.com/faisalfjri/breeze-vue-api/blob/master/src/pages/auth/Login.vue) page.
Since version https://github.com/vueuse/vueuse/releases/tag/v9.3.1 of vueuse the usage of localStorage with useStorage not long work correctly.

**Problem**

The localStorage not sync correctly against userLogin form values in the Login page . The localStorage is synced only one time on first typing in one of the TextInput component.

Any suggestion?

**Comment by alvarofvr** [comment]
Hi guys, any news?

**Comment by faisalfjri** [comment]
hi @alvarofvr, commit #62e1c12 for your problem, I've updated dependencies and fixed login

**Comment by faisalfjri** [comment]
hi @alvarofvr, commit [#62e1c12](https://github.com/faisalfjri/breeze-vue-api/commit/62e1c12dd19174ae1579515a51e9d2a5d39358af) for your problem, I've updated dependencies and fixed login

**Comment by alvarofvr** [comment]
Hi @faisalfjri thank you so much, can you explain the resolution, i'm new in Vue / Pinia and i need some words.
